name: My awesome experience

on: push

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First job step
        run: echo "This is the first job."
  second-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Second job for running script
        run: ./script.sh