name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${06b77b7-81df-4af8-8b95-36fe56e9f90c}
        tenant-id: ${7c0d0625-6ad1-43eb-9d53-c8f368dc92db}
        subscription-id: ${21af4a2f-5e1b-4ffb-a10f-676c742684e3}

    - name: Set up Azure CLI
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az storage -h
    # Development Deployment
    - name: Deploy to Development Storage
      run: |
        az storage blob upload-batch -d \$web --account-name ${https://devstorageacctcamn4j.z29.web.core.windows.net} -s .
        dev_url=$(az storage account show -n ${https://devstorageacctcamn4j.z29.web.core.windows.net} --query "primaryEndpoints.web" --output tsv)
        echo "Development Website URL: $dev_url"
      env:
        AZURE_CLIENT_ID: ${06b77b7-81df-4af8-8b95-36fe56e9f90c}
        AZURE_CLIENT_SECRET: ${F9N8Q~FgcvUZW82YvY95W6zkFKlQY6Udy~2t3dp9}
        AZURE_TENANT_ID: ${7c0d0625-6ad1-43eb-9d53-c8f368dc92db}
        AZURE_SUBSCRIPTION_ID: ${21af4a2f-5e1b-4ffb-a10f-676c742684e3}
      continue-on-error: false   # Stop the workflow if this deployment fails

    # Staging Deployment
    - name: Deploy to Staging Storage
      run: |
        az storage blob upload-batch -d \$web --account-name ${https://stagestorageacctcamn4j.z29.web.core.windows.net} -s .
        stage_url=$(az storage account show -n ${https://stagestorageacctcamn4j.z29.web.core.windows.net} --query "primaryEndpoints.web" --output tsv)
        echo "Staging Website URL: $stage_url"
      env:
        AZURE_CLIENT_ID: ${06b77b7-81df-4af8-8b95-36fe56e9f90c}
        AZURE_CLIENT_SECRET: ${F9N8Q~FgcvUZW82YvY95W6zkFKlQY6Udy~2t3dp9}
        AZURE_TENANT_ID: ${7c0d0625-6ad1-43eb-9d53-c8f368dc92db}
        AZURE_SUBSCRIPTION_ID: ${21af4a2f-5e1b-4ffb-a10f-676c742684e3}
      continue-on-error: false   # Stop the workflow if this deployment fails

    # Production Deployment
    - name: Deploy to Production Storage
      run: |
        az storage blob upload-batch -d \$web --account-name ${https://prodstorageacctcamn4j.z29.web.core.windows.net} -s .
        prod_url=$(az storage account show -n ${https://prodstorageacctcamn4j.z29.web.core.windows.net} --query "primaryEndpoints.web" --output tsv)
        echo "Production Website URL: $prod_url"
      env:
        AZURE_CLIENT_ID: ${06b77b7-81df-4af8-8b95-36fe56e9f90c}
        AZURE_CLIENT_SECRET: ${F9N8Q~FgcvUZW82YvY95W6zkFKlQY6Udy~2t3dp9}
        AZURE_TENANT_ID: ${7c0d0625-6ad1-43eb-9d53-c8f368dc92db}
        AZURE_SUBSCRIPTION_ID: ${21af4a2f-5e1b-4ffb-a10f-676c742684e3}
      continue-on-error: false   # Stop the workflow if this deployment fails
