name: My awesome experience

on: push

jobs: 
  first-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Printing hello
        run: |
          sudo apt install python3
          python3 --version